### ISSUE TITLE
top main navbar positioned behind window controls

### ISSUE THREAD

**Issue by lilllli** [sindresorhus/anatine#130]
![image](https://cloud.githubusercontent.com/assets/4705616/20678356/62e5f98e-b564-11e6-8721-54a621dce039.png)

**Comment by JaKXz** [comment]
This was fixed in a recent release, but is irrelevant now because I believe Twitter has updated their mobile web app.

**Comment by SamVerschueren** [comment]
It's still an issue

![screen shot 2017-01-23 at 08 10 19](https://cloud.githubusercontent.com/assets/1913805/22194540/6c9b9370-e143-11e6-8982-993fcdfe2847.png)
